# Generated by Django 4.1.2 on 2022-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('classpath', models.CharField(max_length=512)),
                ('avatar', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
