# Generated by Django 4.1.2 on 2022-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
