# Generated by Django 4.1.3 on 2022-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_frenchlex"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
