# Generated by Django 4.1.4 on 2023-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatsession_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="online",
            field=models.CharField(default="online", max_length=1024),
        ),
    ]
